version: "1.0.0"

server:
  port: 8080
  shutdown: graceful

# NumEcoEval configs
num-eco-eval:
  base-url: http://localhost:18081
  import-max-memory: 128
num-eco-eval-referential:
  base-url: http://localhost:18080

g4it:
  data:
    retention:
      cron: "0 0 0 * * *"
      oninit: "false"
      day: "14"
  storage:
    retention:
      cron: "0 0 0 * * *"
      oninit: "false"
      day:
        export: "7"
        output: "7"
  cache:
    database:
      ttl: PT20M
    short:
      ttl: PT2M
  organization:
    deletion:
      oninit: "false"
      cron: "0 0 0 * * *"
      day: "7"

filesystem.local.path: "C:\\tmp\\"

spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/g4it
  datasource:
    generate-unique-name: true
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    # kics-scan ignore-line
    password: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: false
      jmx-enabled: false
      max-active: 100
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:/db/changelog/greenitdb.changelog-master.yml

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  codec:
    max-in-memory-size: 100MB
  config:
    import:
      - csv-headers.yml
  servlet:
    multipart:
      resolve-lazily: true
      max-request-size: 100MB
      max-file-size: 100MB

# Batch configs
evaluation:
  batch:
    chunk: 15000
    page-size: 15000
export:
  batch:
    chunk: 15000
    page-size: 15000
loading:
  batch:
    chunk: 15000
    page-size: 15000
    valid-data-writing-enable: false

springdoc:
  swagger-ui:
    tagsSorter: alpha

logging:
  level:
    org.springframework: info
    org.springframework.batch.core:
      job: error
      step: info
      step.ThreadStepInterruptionPolicy: error
      repository.support: error
    org.hibernate: warn
    liquibase: warn
    com.zaxxer: warn
