FROM eclipse-temurin:21-jre
WORKDIR /app
COPY target/*.jar application.jar
COPY storage/--INTERNAL-G4IT-- storage/--INTERNAL-G4IT--
RUN chown -R 1001:1001 /app/storage

USER 1001
EXPOSE 8080
ENTRYPOINT ["java", "-Xmx1g", "-Xms1g", "-jar", "application.jar"]
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 CMD curl -f -s localhost:8080/actuator/health | grep UP || exit 1
