openapi: "3.0.3"
info:
  title: Swagger GreenIT - Open API 3.0 - Administrator
  description: This is a Inventory Server based on the OpenAPI 3.0 specification.
  version: '1.0.0'

tags:
  - name: administrator
    description: Endpoint for subscriber administration

paths:
  /administrator/subscribers:
    get:
      tags:
        - administrator
      summary: Get subscribers information
      operationId: getSubscribers
      responses:
        '200':
          description: Return subscribers information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SubscriberRest"
        '500':
          $ref: "#/components/responses/InternalServerError"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    put:
      summary: Update criteria for a subscriber
      operationId: updateSubscriber
      parameters:
        - $ref: '#/components/parameters/reqSubscriberIdQueryParam'
      requestBody:
        description: Mandatory criteria details to update.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CriteriaRest"
      tags:
        - administrator
      responses:
        '200':
          description: Criteria have been updated for subscriber
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriberRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: "#/components/responses/InternalServerError"
  
  /administrator/organizations:
    get:
      tags:
        - administrator
      summary: Get Organization information
      operationId: getOrganizations
      parameters:
        - $ref: '#/components/parameters/organizationIdQueryParam'
        - $ref: '#/components/parameters/subscriberIdQueryParam'
      responses:
        '200':
          description: Return Organizations information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SubscriberRest"
        '500':
          $ref: "#/components/responses/InternalServerError"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      summary: Update an organization
      operationId: updateOrganization
      parameters:
        - $ref: '#/components/parameters/organizationIdQueryParam'
      requestBody:
        description: Mandatory organization details to update.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrganizationUpsertRest"
      tags:
        - administrator
      responses:
        '200':
          description: Organization has been updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrganizationRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    post:
      summary: Create a new organization
      operationId: createOrganization
      requestBody:
        description: Mandatory organization details to create.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrganizationUpsertRest"
      tags:
        - administrator
      responses:
        '201':
          description: Organization has been created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrganizationRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          description: Organization already exists.
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/RestError"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /administrator/organizations/users:
    get:
      tags:
        - administrator
      summary: Get users related to the organization
      operationId: getUsersOfOrg
      parameters:
        - $ref: '#/components/parameters/reqOrganizationIdQueryParam'
      responses:
        '200':
          description: Return users linked to the Organization.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserInfoRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: "#/components/responses/InternalServerError"
    post:
      summary: Link a user to an org and add roles
      operationId: linkUserToOrg
      requestBody:
        description: Mandatory user and role details to link.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LinkUserRoleRest"
      tags:
        - administrator
      responses:
        '204':
          description: User has been linked to the organization.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserInfoRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          description: User is  already linked to the organization.
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/RestError"
        '500':
          $ref: "#/components/responses/InternalServerError"

    put:
      summary: Edit multiple users' rights
      operationId: updateRoleAccess
      requestBody:
        description: Mandatory user and role details to update.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LinkUserRoleRest"
      tags:
        - administrator
      responses:
        '204':
          description: Rights has been updated.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserInfoRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: Delete user-organization link
      operationId: deleteUserOrgLink
      requestBody:
        description: Mandatory user and organization details to unlink.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LinkUserRoleRest"
      tags:
        - administrator
      responses:
        '204':
          description: link between user and organization has been deleted.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /administrator/subscribers/users:
    get:
      tags:
        - administrator
      summary: search and display the users( filtered by related_domains of subscriber)
      operationId: searchUserByName
      parameters:
        - $ref: '#/components/parameters/nameSearchQueryParam'
        - $ref: '#/components/parameters/reqSubscriberIdQueryParam'
        - $ref: '#/components/parameters/organizationIdQueryParam'
      responses:
        '200':
          description: Return Organizations information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserSearchRest"
        '500':
          $ref: "#/components/responses/InternalServerError"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /administrator/roles:
    get:
      tags:
        - administrator
      summary: Get all the roles
      operationId: getRoles
      responses:
        '200':
          description: Return all the roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RolesRest"
        '500':
          $ref: "#/components/responses/InternalServerError"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'


