openapi: 3.0.3
info:
  title: Swagger GreenIT - Open API 3.0 - Digital Service Indicators
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

tags:
  - name: digital-service indicators
    description: All endpoint for digital service indicators

paths:
  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/indicators:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'
    get:
      tags:
        - digital-service-indicator
      summary: Get indicators from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceIndicatorRest
      responses:
        '200':
          description: return digital service indicators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DigitalServiceIndicatorRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/export:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'
    get:
      summary: endpoint to download digital service indicators export results
      description: endpoint to download digital service indicators export results
      tags:
        - digital-service-indicator
      operationId: getDigitalServiceIndicatorsExportResult
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      responses:
        "200":
          description: return zip file contains all the indicators results
          content:
            application/zip:
              schema:
                type: string
                format: binary
        "400":
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/cloud/indicators:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'
    get:
      tags:
        - digital-service-indicator
      summary: Get cloud indicators from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceCloudIndicatorRest
      responses:
        '200':
          description: return digital service cloud indicators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DigitalServiceCloudIndicatorRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"