version: "3"
networks:
  numecoeval: {}

services:
  postgresdb:
    extends:
      file: shared-docker-compose.yml
      service: postgresdb

  keycloak:
    extends:
      file: shared-docker-compose.yml
      service: keycloak

  api-referentiel:
    extends:
      file: shared-docker-compose.yml
      service: api-referentiel

  api-expositiondonneesentrees:
    extends:
      file: shared-docker-compose.yml
      service: api-expositiondonneesentrees

  api-event-donneesentrees:
    extends:
      file: shared-docker-compose.yml
      service: api-event-donneesentrees

  api-event-calculs:
    extends:
      file: shared-docker-compose.yml
      service: api-event-calculs

  boaviztapi:
    extends:
      file: shared-docker-compose.yml
      service: boaviztapi

  ecomind-api:
    extends:
      file: shared-docker-compose.yml
      service: ecomind-api

  ecologits-api:
    extends:
      file: shared-docker-compose.yml
      service: ecologits-api


      
volumes:
  numecoeval_postgres_data:
    driver: local