version: "3"
networks:
  numecoeval: {}

services:
  kafka:
    extends:
      file: shared-docker-compose.yml
      service: kafka

  postgresdb:
    extends:
      file: shared-docker-compose.yml
      service: postgresdb

  keycloak:
    extends:
      file: shared-docker-compose.yml
      service: keycloak

  api-referentiel:
    extends:
      file: shared-docker-compose.yml
      service: api-referentiel

  api-expositiondonneesentrees:
    extends:
      file: shared-docker-compose.yml
      service: api-expositiondonneesentrees

  api-event-donneesentrees:
    extends:
      file: shared-docker-compose.yml
      service: api-event-donneesentrees

  api-event-calculs:
    extends:
      file: shared-docker-compose.yml
      service: api-event-calculs

  g4it-backend:
    image: g4it/backend:${G4IT_TAG}
    container_name: g4it-backend
    ports:
      - "8080:8080"
    volumes:
      - g4it_storage_data:/app/storage
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:4200"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8180/auth/realms/g4it"
      SPRING_PROFILES_ACTIVE: "local,postgres"
      SPRING_DATASOURCE_HIKARI_MINIMUMIDLE: "2"
      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: "5"
      SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: "120000"
      SPRING_JPA_GENERATEDDL: "false"
      SPRING_JPA_HIBERNATE_DDLAUTO: "none"
      SPRING_LIQUIBASE_CONTEXTS: "!dev"
      SPRINGDOC_SWAGGERUI_CONFIGURL: "/api/v3/api-docs/swagger-config"
      SPRINGDOC_SWAGGERUI_DISABLESWAGGERDEFAULTURL: "true"
      SPRINGDOC_SWAGGERUI_URL: "/api/v3/api-docs"
      BATCH_LOCAL_WORKING_FOLDER_BASE_PATH: "/tmp"
      NUMECOEVAL_BASEURL: "http://api-expositiondonneesentrees:8080"
      NUMECOEVALREFERENTIAL_BASEURL:  "http://api-referentiel:8080"
      NUMECOEVAL_IMPORTMAXMEMORY: "128"
      BOAVIZTAPI_BASEURL: "http://boaviztapi:5000"
      FILESYSTEM_UPLOAD_MAXUPLOADSIZE: "104857600"
      G4IT_STORAGE_RETENTION_CRON: "0 0 7 * * *"
      G4IT_STORAGE_RETENTION_ONINIT: "false"
      G4IT_STORAGE_RETENTION_DAY_EXPORT: "7"
      G4IT_STORAGE_RETENTION_DAY_OUTPUT: "90"
      G4IT_DATA_RETENTION_CRON: "0 30 7 * * *"
      G4IT_DATA_RETENTION_ONINIT: "false"
      G4IT_DATA_RETENTION_DAY: "730"
      FILESYSTEM_LOCAL_PATH: "./storage"
      LOCAL_WORKING_FOLDER: "./storagetmp"
    networks:
      - numecoeval
    depends_on:
      - postgresdb
      - keycloak
      - api-referentiel

  g4it-frontend:
    image: g4it/frontend:${G4IT_TAG}
    container_name: g4it-frontend
    ports:
      - "4200:4200"
    environment:
      URL_INVENTORY: http://localhost:8080/
      FRONTEND_URL: http://localhost:4200
      KEYCLOAK_URL: http://keycloak:8180/auth
      KEYCLOAK_ENABLED: "true"
      MATOMO_TAG_MANAGER_URL : ""
    networks:
      - numecoeval
    depends_on:
      - g4it-backend
      
    boaviztapi:
      extends:
        file: shared-docker-compose.yml
        service: boaviztapi

volumes:
  numecoeval_kafka_data:
    driver: local
  numecoeval_postgres_data:
    driver: local
  g4it_storage_data:
    driver: local