# Les variables globales sont présentes dans le fichier .env
# - POSTGRES (user, password)

version: "3"
networks:
  numecoeval: {}

services:
  # Kafka basé sur la documentation officielle de Bitnami
  ## https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose.yml
  ## https://hub.docker.com/r/bitnami/kafka/
  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "numecoeval_kafka_data:/bitnami"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9091,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091,EXTERNAL://localhost:9092
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: r4zt_wrqTRuT7W2NJsB_GB
      KAFKA_HEAP_OPTS: -Xmx200m -Xms200m
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 300M

  # Postgres basé sur la documentation officielle de Postgres sur Dockerhub
  ## https://hub.docker.com/_/postgres
  postgresdb:
    image: docker.io/postgres:15
    container_name: postgresdb
    hostname: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "numecoeval_postgres_data:/var/lib/postgresql/data"
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 300M

  keycloak:
    image: bitnami/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "8180:8180"
    depends_on:
      - postgresdb
    environment:
      KEYCLOAK_BIND_ADDRESS: 0.0.0.0
      KEYCLOAK_DATABASE_HOST: postgresdb
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_DATABASE_USER: ${POSTGRES_USER}
      KEYCLOAK_HTTP_RELATIVE_PATH: /auth/
      KEYCLOAK_HTTP_PORT: 8180
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_EXTRA_ARGS: --import-realm --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
      JAVA_OPTS_APPEND: -Xms200m -Xmx200m
    volumes:
      - ../../services/keycloak/imports:/opt/bitnami/keycloak/data/import
      - ../../services/keycloak/extensions:/opt/bitnami/keycloak/providers
      - ../../services/keycloak/themes:/opt/bitnami/keycloak/themes
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 300M

  # NumEcoEval
  api-referentiel:
    image: ${REGISTRY_URL}/api-referentiel:${TAG}
    depends_on:
      - postgresdb
    ports:
      - "18080:8080"
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: "90MB"
      SPRING_SERVLET_MULTIPART_MAXFILESIZE: "50MB"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCHSIZE: "1000"
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDERINSERTS: "true"
      SPRING_JPA_SHOWSQL: "false"
      NUMECOEVAL_URLS_ALLOWED: "http://localhost,http://api-referentiel"
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
      JAVA_OPTS: -Xms500m -Xmx500m
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 800M

  api-expositiondonneesentrees:
    image: ${REGISTRY_URL}/api-expositiondonneesentrees:${TAG}
    depends_on:
      - postgresdb
      - api-referentiel
    ports:
      - "18081:8080"
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      NUMECOEVAL_KAFKA_TOPIC_MAX_MESSAGES_SIZE: "52428800"
      NUMECOEVAL_REFERENTIEL_SERVER_URL: "http://api-referentiel:8080"
      SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: "45MB"
      SPRING_SERVLET_MULTIPART_MAXFILESIZE: "10MB"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_GENERATESTATISTICS: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDERINSERTS: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCHSIZE: "1000"
      SPRING_JPA_SHOWSQL: "false"
      NUMECOEVAL_URLS_ALLOWED: "http://localhost,http://api-expositiondonneesentrees"
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
      NUMECOEVAL_CALCULS_SERVER_URL: "http://api-event-calculs:8080"
      JAVA_OPTS: -Xms256m -Xmx256m
      REGLEPARDEFAUTDUREEUSAGE: REEL
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 400M

  api-event-donneesentrees:
    image: ${REGISTRY_URL}/api-event-donneesentrees:${TAG}
    depends_on:
      - kafka
      - postgresdb
    ports:
      - "18083:8080"
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9091"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
      JAVA_OPTS: -Xms90m -Xmx90m
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 150M

  api-event-calculs:
    image: ${REGISTRY_URL}/api-event-calculs:${TAG}
    depends_on:
      - kafka
      - postgresdb
    ports:
      - "18085:8080"
    environment:
      SERVER_PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8080"
      NUMECOEVAL_URLS_ALLOWED: "http://localhost,http://api-event-calculs"
      NUMECOEVAL_REFERENTIELS_URL: "http://api-referentiel:8080"
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9091"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/postgres?reWriteBatchedInserts=true"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      LOGGING_LEVEL_ROOT: $LOGGING_LEVEL_ROOT
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: $LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
      JAVA_OPTS: -Xms140m -Xmx140m
    networks:
      - numecoeval
    deploy:
      resources:
        limits:
          memory: 220M

  #BoaviztAPI
  boaviztapi:
    image: ghcr.io/boavizta/boaviztapi:1.3
    container_name: boaviztapi
    ports:
      - "5000:5000"
    networks:
      - numecoeval
      
volumes:
  numecoeval_kafka_data:
    driver: local
  numecoeval_postgres_data:
    driver: local
