# Use an official Maven image as the base image
FROM node:20-alpine as build

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install -g @angular/cli@17.3.8
RUN npm install
RUN npm run build

FROM nginx:latest
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html
COPY --from=build /usr/src/app/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/nginx/25-inject-env-var.sh /docker-entrypoint.d/25-inject-env-var.sh

USER root

RUN chmod a+rwx -R /usr/share/nginx/html
RUN chmod a+x /docker-entrypoint.d/25-inject-env-var.sh
RUN chown -R nginx:nginx /var/cache/nginx

CMD ["nginx", "-g", "daemon off;"]

USER nginx
EXPOSE 4200
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 CMD curl -f -s localhost:4200 || exit 1
