# Use an official Maven image as the base image
FROM node:20-alpine

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install -g @angular/cli@17.3.8
RUN npm install
RUN npm run build

FROM nginx:latest

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# js resources to inject env variables
ENV JSFOLDER=/usr/share/nginx/html
# script to replace env variable before start
COPY ./nginx/25-inject-env-var.sh /docker-entrypoint.d/25-inject-env-var.sh
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html

USER root

RUN chmod a+rwx -R /usr/share/nginx/html
RUN chmod a+x /docker-entrypoint.d/25-inject-env-var.sh
RUN chown -R nginx:nginx /var/cache/nginx

CMD ["nginx", "-g", "daemon off;"]

USER nginx
EXPOSE 4200
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 CMD curl -f -s localhost:4200 || exit 1
