name: Backend - Build and Test
on:
  pull_request:
    paths:
      - "services/backend/**"
      - ".github/workflows/**"
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Run the Maven verify phase
        run: |
          cd services/backend
          mvn verify -q
