openapi: "3.0.3"
info:
  title: Swagger GreenIT - Open API 3.0 - Inventory Loading and Evaluating
  description: This is a Inventory Server based on the OpenAPI 3.0 specification.
  version: '1.0.0'

tags:
  - name: inventory-evaluating
    description: All endpoint for the organization's inventory evaluating

paths:
  /subscribers/{subscriber}/organizations/{organization}/inventories/{inventoryId}/evaluating:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/inventoryIdPathParam'
      - in: header
        name: Accept-Language
        schema:
          type: string
    post:
      summary: Launch evaluation batch
      operationId: launchEvaluating
      x-custom-role: "hasRole('INVENTORY_WRITE')"
      tags:
        - inventory-evaluating
      responses:
        '200':
          description: The task id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskIdRest"
        '400':
          $ref: "#/components/responses/BadRequestError"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/evaluating:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - in: path
        name: digitalServiceUid
        schema:
          type: string
        required: true
        description: The digital service UID.
      - in: header
        name: Accept-Language
        schema:
          type: string
    post:
      summary: Launch evaluation batch
      operationId: launchEvaluatingDigitalService
      x-custom-role: "hasRole('DIGITAL_SERVICE_WRITE')"
      tags:
        - inventory-evaluating
      responses:
        '200':
          description: The task id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskIdRest"
        '400':
          $ref: "#/components/responses/BadRequestError"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"