openapi: 3.0.3
info:
  title: Swagger GreenIT - Open API 3.0 - Digital Service Indicators
  description: This is a GreenIT Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

tags:
  - name: digital-service-outputs
    description: Endpoint for digital service outputs

paths:
  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/outputs/physical-equipments:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'
    get:
      tags:
        - digital-service-outputs
      summary: Get physical equipments from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceOutputsPhysicalEquipmentsRest
      responses:
        '200':
          description: return digital service output physical equipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutPhysicalEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/outputs/virtual-equipments:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'
    get:
      tags:
        - digital-service-outputs
      summary: Get virtual equipments from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceOutputsVirtualEquipmentsRest
      responses:
        '200':
          description: return digital service output virtual equipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutVirtualEquipmentRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /subscribers/{subscriber}/organizations/{organization}/digital-services/{digitalServiceUid}/outputs/applications:
    parameters:
      - $ref: '#/components/parameters/subscriberPathParam'
      - $ref: '#/components/parameters/organizationPathParam'
      - $ref: '#/components/parameters/digitalServiceUidPathParam'
    get:
      tags:
        - digital-service-outputs
      summary: Get applications from one digital service
      x-custom-role: "hasRole('DIGITAL_SERVICE_READ')"
      operationId: getDigitalServiceOutputsApplicationsRest
      responses:
        '200':
          description: return digital service output applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutApplicationRest"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: "#/components/responses/InternalServerError"
