name: Dependency Check Backend

on:
  push:
    branches: ["main"]
    paths:
      - services/backend/**

jobs:
  build:
    name: Build and analyze dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Build project with Maven
        run: |
          cd services/backend
          mvn clean install -P SKIP-ALL-TEST
          rm -rf storage
          rm -rf storagetmp
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "backend"
          path: "services/backend"
          format: "HTML"
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
