name: Frontend - Build - Test - Analyze
on:
  pull_request:
    paths:
      - "services/frontend/**"
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: services/frontend/package-lock.json
      - name: Install dependencies and run tests
        run: |
          cd services/frontend
          npm ci
          npm run test:ci
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: services/frontend
