name: "Update Angular Action"
on:
  schedule:
    - cron: "30 5 * * 1,3,5"

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Updating ng dependencies
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          repo-token: $
          project-path: services/frontend
