name: Keycloak Docker Image Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
    paths:
      - "services/keycloak/**"
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - name: Extract branch or tag name
        id: extract_ref
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            REF_NAME=${GITHUB_REF#refs/tags/}
          elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            REF_NAME=${GITHUB_REF#refs/heads/}
          else
            REF_NAME=${GITHUB_HEAD_REF#refs/heads/}
          fi
          REF_NAME=$(echo "${REF_NAME}" | tr '/' '_')
          echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: g4it/keycloak
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: services/keycloak
          tags: ${{ env.REF_NAME }}
